import Head from 'next/head';
import Script from 'next/script';
import VoiceAssistantProvider from './context/VoiceAssistantProvider';
import DigitalHumanContainer from './components/DigitalHumanContainer/DigitalHumanContainer.component';
import ConversationContainer from "./components/ConversationContainer/ConversationContainer.component"
import HeaderContainer from './components/HeaderContainer/HeaderContainer.component'

export default function Home() {
  return (
    <>
      <Head>
        <title>🎓 ChatCampus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script id="live2D_2" src="/library/live2d.min.js"> </Script>
      <Script id="live2D_4" src="/library/live2dcubismcore.js"></Script>
      <VoiceAssistantProvider>
      <div className="md:h-screen flex flex-col bg-gradient-to-bl from-red-50 via-orange-50 to-yellow-50">
        <HeaderContainer/>
        <main className="flex-grow grid grid-cols-1 md:grid-cols-3 gap-6 p-6">
          <DigitalHumanContainer />
          <ConversationContainer />
        </main>
      </div>
        </VoiceAssistantProvider>
    </>
  );
}